server:
  port: 9042
  error:
    path: /error
    whitelabel:
      enabled: true
  servlet:
    context-path: /realname-auth
  tomcat:
    basedir: tmp/realname-auth
    uri-encoding: UTF-8
    min-spare-threads: 7 # Minimum amount of worker threads.
    max-http-post-size: 100MB # Maximum size of the HTTP post content.
    max-connections: 10000 # Maximum number of connections that the server accepts and processes at any given time.
    max-threads: 200 # Maximum amount of worker threads.
    max-swallow-size: 100MB # Maximum amount of request body to swallow.

spring:
  mvc:
    throw-exception-if-no-handler-found: true #404抛异常，交给程序处理
  application:
    name: realname-auth
  http:
    encoding:
      enabled: true
      charset: UTF-8
  redis:
    database: 0 #索引（默认为0）
    host: 127.0.0.1 #地址
    port: 6379 #端口号
    #password:  #连接密码（默认空）
    timeout: 6000
    pool:
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）

hystrix: 
   command: 
      default: 
         circuitBreaker: 
            sleepWindowInMilliseconds: 1000 #断路器，断路器跳闸后等待多长时间重试
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 5000 #断路器，请求发出后多长时间超时

ribbon:
   ConnectTimeout: 30000 #ribbon连接到服务端的超时时间
   ReadTimeout: 30000 #ribbon连接到服务端后，多长时间没有获取到响应的超时时间